{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /api/v3/positions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b38e550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))","timestamp":"2024-04-14 19:17:05,912+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /api/v3/positions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b291510>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))","timestamp":"2024-04-14 20:39:09,312+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/depth?symbol=NSE%3ANIFTYBANK-INDEX&ohlcv_flag=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11d568d50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))","timestamp":"2024-04-15 00:17:56,874+0530","service":"FyersDataSocket"}
